FROM face-clock-frontend:v0 AS build
WORKDIR /app
COPY . .
RUN npm run build -- --output-path=dist/app
FROM nginx:alpine
COPY --from=build /app/dist/app /usr/share/nginx/html
COPY k8s/nginx.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /var/cache/nginx/client_temp /run && chown -R nginx:nginx /usr/share/nginx/html /var/cache/nginx /run
CMD ["nginx", "-g", "daemon off;"]
