apiVersion: v1
kind: Service
metadata:
  name: milvus-database
spec:
  type: ClusterIP
  selector:
    app: milvus-database
  ports:
    - name: grpc
      protocol: TCP
      port: 19530
      targetPort: 19530
    - name: http
      protocol: TCP
      port: 9091
      targetPort: 9091
