backend:
  image:
    repository: face-clock-backend
    tag: v1
  service:
    type: NodePort
    port: 5000
    nodePort: 30500
frontend:
  image:
    repository: face-clock-frontend
    tag: v1
  service:
    type: NodePort
    port: 4200
    nodePort: 30420
database:
  image:
    repository: milvusdb/milvus
    tag: v2.6.3
  service:
    type: ClusterIP
    port1: 19530
    port2: 9091
automountServiceAccountToken: false
