backend:
  image:
    repository: face-clock-backend
    tag: v1
  service:
    type: NodePort
    port: 5000
    nodePort: 30500
frontend:
  image:
    repository: face-clock-frontend
    tag: v1
  service:
    type: NodePort
    port: 80
    nodePort: 30080
  ingress:
    enabled: true
    host: frontend.local
    path: /

